#!/bin/bash
current_date=$(date "+%Y.%m.%d")
log_name=logs/update_inv_no_pfg.log
exec &> $log_name.$current_date
set -o errexit

php_log_name=logs/inventory_update_no_pfg.log
php inventory_update_no_pfg.php > $php_log_name.$current_date
rc=$? # this is the return code from php job, since it always returns 0 on exit(<some message>);

if [ $rc = 0 ]; then
	cd /var/www/html/magmi/cli/
	sudo chown ec2-user ../state/progress.txt
	sudo chmod 755 ../state/progress.txt

	echo magmi import Brock stock changes
	php magmi.cli.php -mode=update -CSV:filename="/var/www/html/var/import/brock-stock.csv"
	echo magmi import Brock price changes
	php magmi.cli.php -mode=update -CSV:filename="/var/www/html/var/import/brock-price.csv"

	echo magmi import days without sales
	php magmi.cli.php -profile=DefaultNOM2e -mode=update -CSV:filename="/var/www/html/var/import/dws.csv"
	php magmi.cli.php -profile=DefaultNOM2e -mode=update -CSV:filename="/var/www/html/var/import/yesterday-sales.csv"

	echo zipping up inventory files
	zip -m "daily-inv-archive-$(date +"%Y-%m-%d").zip" dws.csv yesterday-sales.csv brock-stock.csv brock-price.csv
	cd archive/
	mv ../daily-inv-archive-*.zip .

fi

