<div class="footer-container">
    <div class="footer">
		
		<div class="col1">
			<img src="<?php echo($this->getSkinUrl('images/logo_footer.gif')) ?>" height="19" width="164" alt="Mojo Parts" /><br/>
			<ul class="first">
				<li><a href="/lighting">Lighting</a></li>
				<li><a href="/body-mirrors">Body &amp; Mirrors</a></li>
				<li><a href="/engine-drivetrain">Engine &amp; Drivetrain</a></li>
			</ul>
			<ul>
	 			<li><a href="/about-mojo-parts">About Us</a></li>
				<li><a href="/contacts">Contact Us</a></li>
				<li><a href="/warranty">Warranty</a></li>
				<li><a href="/return-policy">Return Policy</a></li>
				<li><a href="/customer-service">Customer Service</a></li>
				<li><a href="/secure-shopping">Secure Shopping</a></li>
			</ul>
		</div>

		<div class="col2">
			<strong>Trusted Auto Parts Provider</strong>
			<img src="<?php echo($this->getSkinUrl('images/footer_ssl.gif')) ?>" height="99" width="66" alt="InstantSSL" />
			<img src="<?php echo($this->getSkinUrl('images/footer_sema.gif')) ?>" height="99" width="73" alt="SEMA" />
			<img src="<?php echo($this->getSkinUrl('images/footer_webtrust.gif')) ?>" height="99" width="65" alt="WebTrust" />
			<img src="<?php echo($this->getSkinUrl('images/footer_paypal.gif')) ?>" class="last" height="99" width="77" alt="PayPal Verified" />
		</div>

        <p>&copy; <?php echo date('Y'); ?> Mojo Parts. All rights reserved. <a href="privacy-policy">Privacy Policy</a><!-- &nbsp;&nbsp;|&nbsp;&nbsp;<a href="#">Sitemap</a> --></p>
    </div>
</div>
