<div id="block_notice_amazon_other_listings_grid" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('3rd Party Listings'); ?>">
    <?php
    echo Mage::helper('M2ePro')->__('
        This Page shows <strong>Accounts</strong> and <strong>Marketplaces</strong> that have 3rd Party Listings associated with them. (3rd Party Listings are Listings that haven\'t been Added by M2E Pro.)<br/><br/>
        You can <strong>Map</strong> these Listings to existing Products in Magento and <strong>Move</strong> them to another M2E Pro Listings for further management.<br/>
        For that use Single Actions on appropriate Listing record or use Mass Actions in the top right corner.<br/><br/>
        <strong>Note</strong>: To import 3rd Party Listings the <strong>Import 3rd Party Listings</strong> must be <strong>enabled</strong> in Account\'s Settings (%menu_account_edit_3rd_path%)
        and the <strong>3rd Party Listings Synchronization</strong> must be <strong>enabled</strong> in (%menu_synchronization_path%).',
        Mage::helper('M2ePro/View_Amazon')->getPageNavigationPath('configuration', 'Accounts', '', '[Needed Account] > 3rd Party Listings Tab'),
        Mage::helper('M2ePro/View_Amazon')->getPageNavigationPath('configuration', 'Synchronization', 'any')
    );

    $url = Mage::helper("M2ePro/Module_Support")->getDocumentationUrl(NULL, NULL, "x/gogVAQ");

    echo Mage::helper('M2ePro')->__('
            <br/><br/>More detailed information about ability to work with this Page you can find <a href="%url%" target="_blank">here</a>.',
        Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(Ess_M2ePro_Helper_Component_Amazon::NICK, '3rd+Party+Listings')
    );
?>
</div>