
<div class="block block-layered-nav">
    <div class="block-title">
        <strong><span><?php echo $this->__('Categories') ?></span></strong>
    </div>
    <div class="block-content">
        <dl id="narrow-by-list">
        	<dd class="leftnav">
        		<ol>
					<?php foreach ($this->getStoreCategories() as $_category): ?>                        	
            			<li><a href="<?=$this->getCategoryUrl($_category)?>" <? if ($this->isCategoryActive($_category)): ?> class="active" <? endif; ?>><?=$_category->getName()?></a></li>                       	
					<?php endforeach; ?>
				</ol>
			</dd>
		</dl>
        <script type="text/javascript">decorateDataList('narrow-by-list')</script>
    </div>
</div>

